In [1]:
import numpy as np
import os
%matplotlib inline
import matplotlib as mpl
import matplotlib.pyplot as plt

In [2]:
np.random.seed(4)
m = 60
w1, w2 = 0.1, 0.3
noise = 0.1

angles = np.random.rand(m) * 3 * np.pi / 2 - 0.5
X = np.empty((m, 3))
X[:, 0] = np.cos(angles) + np.sin(angles)/2 + noise * np.random.randn(m) / 2
X[:, 1] = np.sin(angles) * 0.7 + noise * np.random.randn(m) / 2
X[:, 2] = X[:, 0] * w1 + X[:, 1] * w2 + noise * np.random.randn(m)

In [3]:
X_centered = X - X.mean(axis=0)
U, s, Vt = np.linalg.svd(X_centered)
c1 = Vt.T[:, 0]
c2 = Vt.T[:, 1]

In [11]:
m, n = X.shape
S = np.zeros(X_centered.shape)
S[:n, :n] = np.diag(s)

In [11]:
np.allclose(X_centered, U.dot(S).dot(Vt))

True

In [14]:
W2 = Vt.T[:, :2]
X2D = X_centered.dot(W2)

X2D_using_svd = X2D

In [12]:
from sklearn.decomposition import PCA

pca = PCA(n_components=2)
X2D = pca.fit_transform(X)

In [13]:
X2D[:5]

array([[ 1.26203346,  0.42067648],
       [-0.08001485, -0.35272239],
       [ 1.17545763,  0.36085729],
       [ 0.89305601, -0.30862856],
       [ 0.73016287, -0.25404049]])

In [15]:
X2D_using_svd[:5]

array([[-1.26203346, -0.42067648],
       [ 0.08001485,  0.35272239],
       [-1.17545763, -0.36085729],
       [-0.89305601,  0.30862856],
       [-0.73016287,  0.25404049]])

In [19]:
X3D_inv = pca.inverse_transform(-X2D)
X3D_inv

array([[-1.01450604, -0.54656333, -0.27441525],
       [-0.02103231,  0.55108376,  0.18101894],
       [-0.95379477, -0.4668077 , -0.24237013],
       [-0.91717404,  0.22083765, -0.01049779],
       [-0.74607229,  0.22027492,  0.00492637],
       [ 1.12690818,  0.35694801,  0.22123723],
       [-1.00841533, -0.59221383, -0.28903096],
       [ 0.6752935 , -0.26696466, -0.02731797],
       [ 1.03283361,  0.57607012,  0.28547668],
       [ 0.54623317,  0.6650994 ,  0.27066755],
       [-0.9923746 , -0.00122416, -0.09115874],
       [ 1.12210694,  0.24451191,  0.18343231],
       [-0.99154967, -0.26167174, -0.17764026],
       [-0.93838688, -0.4658921 , -0.24066004],
       [ 1.09614136,  0.15310678,  0.15068578],
       [-0.35049411,  0.43714153,  0.11309173],
       [ 0.68847757, -0.28266102, -0.03133157],
       [ 0.6789737 ,  0.68944696,  0.29087031],
       [ 0.87367465, -0.18133188,  0.01924123],
       [-1.07138066, -0.52030841, -0.27087892],
       [ 0.53326349,  0.70190846,  0.281

In [17]:
np.allclose(X3D_inv, X)

False